baseURL = "https://seraphin.cloud/"
languageCode = "en-gb"
paginate = 6
theme = "portio"
title = "Seraphin Iot Wireless Monitoring and Telemetry Platform"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2


# Sitemap Menu
[[menu.sitemap]]
name = "About"
url = "/#about"
weight = 1
# [[menu.sitemap]]
# name = "Frequently Ask Question"
# url = "#"
# weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "/legal/privacy"
weight = 3
[[menu.sitemap]]
name = "Terms and Conditions"
url = "/documents/tnc.pdf"
weight = 3
# [[menu.sitemap]]
# name = "Latest Article"
# url = "#"
# weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All rights reserved © Ionas Software Ltd 2023"
footerLogo = "images/site-navigation/256x256.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
#logo = "images/site-navigation/logo.png"
logo = "images/site-navigation/logo.svg"

[params.address]
address = "Ionas Software Ltd, 34 Craggan Drive, G14 0EW, Glasgow, UK"
email = "contact@ionas.co.uk"
openingHours = "Contact us between 10am to 5pm Monday to Friday"
phone = "+44 (0) 141 237 4636"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/ionassoftware/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/company/20872243/"
weight = 2
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"
# weight = 3
