baseURL = "https://seraphin.cloud/"
pagination.pagerSize = 6

theme = "portio"

defaultContentLanguage = 'en'
# defaultContentLanguageInSubdir = true
# disableDefaultLanguageRedirect = true


[languages]
  [languages.en]
    contentDir = 'content/en-gb'
    languageName = 'English'
    languageCode = "en-gb"
    languageDirection = 'ltr'
    title = "Seraphin Iot Wireless Monitoring and Telemetry Platform"
    weight = 1
    [languages.en.params]
      subtitle = 'Iot Monitoring and Telemetry Platform'
      blogPageURL = "blog"
      contactLink = "contact"
      copyright = "All rights reserved © Ionas Software Ltd 2023"
      navbarCta = "Request demo"
      navbarContact = "Contact"
      footerCta = "Deploy Seraphin IoT Platform at your site"
      footerCtaBtn = "Get in touch"
      footerContactUs = "Contact us"
      footerContact = "Contact"
      footerSitemap = "Sitemap"
      footerLogo = "images/site-navigation/256x256.png"
      formspreeURL = "YOUR FORMSPREE URL"
      googleAnalytics = "UA-226688431-1"
      #logo = "images/site-navigation/logo.png"
      logo = "/images/site-navigation/logo.svg"

    [languages.en.params.address]
      address = "Ionas Software Ltd, 34 Craggan Drive, G14 0EW, Glasgow, UK"
      email = "contact@ionas.co.uk"
      openingHours = "Contact us between 10am to 5pm Monday to Friday"

    [languages.en.params.map]
      APIkey = "YOUR GOOGLE MAP API"
      latitude = "23.7783741"
      longitude = "90.3746808"
      pinImage = "images/pin.png"

    # Social icons
    [[languages.en.params.social]]
      icon = "fa-facebook-official"
      url = "https://www.facebook.com/ionassoftware/"
      weight = 1
    [[languages.en.params.social]]
      icon = "fa-linkedin-square"
      url = "https://www.linkedin.com/company/20872243/"
      weight = 2
    # [[params.social]]
    # icon = "fa-twitter-square"
    # url = "https://twitter.com/"
    # weight = 3

    # Main Menu
    [[languages.en.menu.main]]
    name = "Home"
    url = "#home"
    weight = 1
    [[languages.en.menu.main]]
    name = "About"
    url = "#about"
    weight = 2
    [[languages.en.menu.main]]
    name = "Use Cases"
    url = "#use-cases-across-various-industries"
    weight = 3
    [[languages.en.menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 4
    [[languages.en.menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

    # Sitemap Menu
    [[languages.en.menu.sitemap]]
    name = "About"
    url = "/#about"
    weight = 1

    [[languages.en.menu.sitemap]]
    name = "Privacy & Policy"
    url = "/legal/privacy"
    weight = 3


  [languages.pl]
    contentDir = 'content/pl-pl'
    languageName = 'Polski'
    languageDirection = 'ltr'
    title = "Platforma telemetryczna i monitorująca Seraphin Iot"
    weight = 1
    [languages.pl.params]
      subtitle = 'Platforma telemetryczna i monitorująca Iot'
      blogPageURL = "blog"
      contactLink = "kontakt"
      copyright = "Wszystkie prawa zastrzeżone © Ionas Software Ltd 2023"
      navbarCta = "Zamów demonstrację"
      navbarContact = "Kontakt"
      footerLogo = "images/site-navigation/256x256.png"
      footerCta = "Wprowadź platformę Seraphin IoT w swojej firmie"
      footerCtaBtn = "Skontaktuj się z nami"
      footerContactUs = "Skontaktuj się z nami"
      footerContact = "Kontakt"
      footerSitemap = "Mapa strony"
      formspreeURL = "YOUR FORMSPREE URL"
      googleAnalytics = "UA-226688431-1"
      #logo = "images/site-navigation/logo.png"
      logo = "images/site-navigation/logo.svg"

    [languages.pl.params.address]
      address = "Szymon Czaja - Programowanie w chmurze, ul. Gołębiowskiego 10, 38-130 Frysztak"
      email = "contact@ionas.co.uk"
      openingHours = "Skontaktuj się z nami między 10:00 a 17:00 od poniedziałku do piątku"

    # Main Menu
    [[languages.pl.menu.main]]
    name = "O produkcie"
    url = "#o-platformie-seraphin-iot"
    weight = 2
    [[languages.pl.menu.main]]
    name = "Zastosowania"
    url = "#zastosowania"
    weight = 3
    [[languages.pl.menu.main]]
    name = "Wycena"
    url = "/wycena"
    weight = 4
    [[languages.pl.menu.main]]
    name = "Kontakt"
    url = "/kontakt"
    weight = 5

    # Sitemap Menu
    [[languages.pl.menu.sitemap]]
    name = "O nas"
    url = "#o-platformie-seraphin-iot"
    weight = 1

    [[languages.pl.menu.sitemap]]
    name = "Polityka prywatności"
    url = "prawne/polityka-prywatnosci"
    weight = 3