site_name: Seraphin Documentation

theme:
  name: material
  favicon: ../assets/favicon.ico
  logo: ../assets/logo.svg
  custom_dir: docs/overrides
  features:
    - navigation.tracking

extra_css:
  - ../styles/extra.css

extra:
  homepage: https://seraphin.cloud
